### ISSUE TITLE
Qt5

### ISSUE THREAD

**Issue by sanguinariojoe** [SAP/fedem-gui#20]
Related to https://github.com/SAP/fedem-gui/issues/17

Ok, it seems the whole problem on my system is Qt4. Would you be interested on upgrading to Qt5?

**Comment by kmoks** [comment]
I see. Well, porting the GUI code to Qt5 or later is a big endeavor and it might require quite some code changes for everything to work as before. We actually started to port everything to Qt6 recently, on a side branch before we went open source. So it is perhaps even better to continue on that track instead of spending the effort to go view Qt5. In any case, some of the other third party libraries might require an update as well.

I'll see if I can put that Qt6 branch out on this repo soon, in case you want to have a look.

**Comment by sanguinariojoe** [comment]
Sure! Qt6 even better!

I really want to be out of your way. So feel let me know if you rather want me to contribute or you think I will be just hampering the process

**Comment by kmoks** [comment]
No, all contributions are welcome, and appreciated. Make no doubts about that!
One note: When raising more general questions about the code, like this one. You can also use the Discussions tab in github.

**Comment by sanguinariojoe** [comment]
Oki! I am waiting then for such Qt6 branch

**Comment by kmoks** [comment]
@sanguinariojoe Here is the current Qt6 branch: https://github.com/kmoks/fedem-gui/tree/qt6-port.

I pushed it to my personal fork only as this is work in progress. I have verified that it builds on my Windows system - but not tested on Linux/gcc. There are a lot of commits there which will be squashed (most of them) before this will be merged. But this way it is easier to track issues and bugs related to different code changes.

Notice: You need to configure with `-DUSE_QWTLIB=OFF` since the version of Qwt included is not compliant with Qt6 (or Qt5). This means that the 2D curve plotting feature is not available. We'll do that later (feel free to contribute on updating the Qwt library). You may also need `-DUSE_COMAPI=OFF`, at least when building on Windows, as the src/comApi sources have not yet been ported to Qt6.

Also notice there is an associated update in the fedem-mdb repository, in the branch https://github.com/SAP/fedem-mdb/tree/qt6-port. You'll need this also for a successful build. The submodule reference in this repository is updated to reflect this.

Feel free to fork this repository and commit changes to your own branch as you discover issues to be fixed (I'm sure there will be some). It is better than adding a new Issue in this repository for each item. Then we can clean up the history at then end when things work.

Thanks, and Good luck!
